### ISSUE TITLE
Error causing NumberPicker to not snap to the closest value after a fling/scroll

### ISSUE THREAD

**Issue by Elektroktay** [Carbs0126/NumberPickerView#3]
Hey it's me again! :smile: 

I'm using the NumberPicker inside a RecyclerView, inside a NestedScrollView. I have the version 1.0.3. I noticed that when I call nofifyItemChanged(int) on the item that contains the NumberPicker, the NumberPicker sometimes goes "numb", as in it doesn't attach to the closest value when I scroll anymore. When this happens, it gives me the following exception:
`07-09 14:49:25.379 7829-7829/com.*****.******** W/MessageQueue: Handler (cn.carbswang.android.numberpickerview.library.NumberPickerView$1) {d43ee1b} sending message to a Handler on a dead thread
                                                                   java.lang.IllegalStateException: Handler (cn.carbswang.android.numberpickerview.library.NumberPickerView$1) {d43ee1b} sending message to a Handler on a dead thread
                                                                       at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
                                                                       at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                       at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                       at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                       at cn.carbswang.android.numberpickerview.library.NumberPickerView.onTouchEvent(NumberPickerView.java:933)
                                                                       at android.view.View.dispatchTouchEvent(View.java:8547)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
                                                                       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
                                                                       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2372)
                                                                       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1722)
                                                                       at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
                                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2333)
                                                                       at android.view.View.dispatchPointerEvent(View.java:8742)
                                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4136)
                                                                       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4002)
                                                                       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3557)
                                                                       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3610)
                                                                       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3576)
                                                                   	at an`

Here is how I initialize the NumberPicker:

`
            final String[] servings = new String[]{"01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
                    "11", "12", "13", "14", "15", "16", "17", "18", "19", "20"};
            //holder.servings is the NumberPicker.
            holder.servings.setMinValue(1);
            holder.servings.setDisplayedValues(servings);
            holder.servings.setMaxValue(20);
            if (currentRecipe.serves > 0)
                holder.servings.setValue(currentRecipe.serves);
            else
                holder.servings.setValue(1);
            holder.servings.setOnValueChangedListener(new NumberPickerView.OnValueChangeListener() {
                @Override
                public void onValueChange(NumberPickerView picker, int oldVal, int newVal) {
                    RecipeIngredientsAdapter.this.servings = newVal;
                    RecipeIngredientsAdapter.this.notifyItemRangeChanged(0, getItemCount()-1);
                }
            });`

Here's the layout:
`        <cn.carbswang.android.numberpickerview.library.NumberPickerView
            android:id="@+id/recipe_ingredients_servings"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:background="@android:color/transparent"
            app:npv_ItemPaddingHorizental="5dp"
            app:npv_TextColorNormal="@android:color/white"
            app:npv_TextColorSelected="@android:color/white"
            android:layout_gravity="center_horizontal|top"
            app:npv_ShowCount="1"
            app:npv_MinValue="1"
            app:npv_MaxValue="20"
            app:npv_ShowDivider="false"
            app:npv_TextSizeNormal="40sp"
            app:npv_TextSizeSelected="40sp"
            app:npv_WrapSelectorWheel="false"/>`

(By the way, I noticed you mistyped npv_ItemPaddingHorizental)

**Comment by Carbs0126** [comment]
it's a little complicate, and i'm on it now. 
maybe it caused by the 'recycle mechanism', the ListView and RecycleView use recycled view to display different data.
I will notice you if i have solved this problem. how to comminucate with you? via skype? my account is yeah0126@yeah.net

**Comment by Carbs0126** [comment]
one of fast solutions is to get NumberPickerView out of RecycleView, add NumberPickerView in NestScrollView, but not in RecycleView

**Comment by Carbs0126** [comment]
i have added code to prevent HandlerThread of being invalid, you can try again, but i highly recommad that better not use NumberPickerView in ListView or RecyclerView
