### ISSUE TITLE
什么情况下会导致这个问题呢？getWillPickIndexByGlobalY illegal index : 178 getOneRecycleSize() : 171 mWrapSelectorWheel : false

### ISSUE THREAD

**Issue by axkza** [Carbs0126/NumberPickerView#59]
Fatal Exception: java.lang.IllegalArgumentException: getWillPickIndexByGlobalY illegal index : 178 getOneRecycleSize() : 171 mWrapSelectorWheel : false
       at cn.carbswang.android.numberpickerview.library.NumberPickerView.getWillPickIndexByGlobalY(NumberPickerView.java:931)
       at cn.carbswang.android.numberpickerview.library.NumberPickerView.access$100(NumberPickerView.java:26)
       at cn.carbswang.android.numberpickerview.library.NumberPickerView$1.handleMessage(NumberPickerView.java:365)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:232)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Carbs0126** [comment]
这个fatal是NumberPickerView主动抛出来的，原因是，当前的item一共有171个，而给的索引值是178，超出了范围。可以参考这个项目的readme文件，或者android原生的numberpicker的做法：
即：
如果更改后的item变少了，需要先setmin、setmax，然后setDisplayValue
